### ISSUE TITLE
[BUG] scrapeYt.getVideo(videoID); throws an error when trying to get a video with no description

### ISSUE THREAD

**Issue by th13n-h4ck3r** [VincentJonathan/scrape-yt#18]
Thank you so much for making this repo possible. This repo has everything I needed.

**Describe the bug**
[Here](https://youtu.be/pbNjHBM47bs) is the url to the video that `scrapeYt.getVideo(videoID)` throws the error.

**The error**
`TypeError: Cannot read property 'runs' of undefined
    at Object.parseGetVideo (node_modules\scrape-yt\dist\common\parser.js:364:31)
    at node_modules\scrape-yt\dist\index.js:196:64
    at step (node_modules\scrape-yt\dist\index.js:44:23)
    at Object.next (node_modules\scrape-yt\dist\index.js:25:53)
    at fulfilled (node_modules\scrape-yt\dist\index.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**To Reproduce**
use `scrapeYt.getVideo(videoID)` where `videoID` is a video without a description like this [one](https://youtu.be/pbNjHBM47bs) I found.

**Expected behavior**

**Additional context**
I think it's because the code always expect a description on every video. I could be wrong.

**Comment by SuspiciousLookingOwl** [comment]
Glad you like it!

The error is fixed on `1.4.2`, please update the package.

`npm update scrape-yt`
